### Create player
POST http://localhost:3000/players/
Content-Type: application/json

{
  "name": "Alex",
  "rating": 85
}


### Get players
GET http://localhost:3000/players/


### Generate Team
POST http://localhost:3000/teams/
Content-Type: application/json

{
  "playerIds": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Alex",
  "email": "alex123@example.com",
  "password": "password123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "alex@example.com",
  "password": "password123"
}